- apps/web/app/components/ui/breadcrumb.tsx
- apps/web/app/modules/Courses/CourseView/CourseViewMainCard.tsx
- apps/web/app/modules/Courses/CourseView/LessonsList.tsx
- apps/web/app/modules/Courses/Lesson/Lesson.page.tsx
- apps/web/app/modules/Courses/Lesson/LessonItems/Questions.tsx
- apps/web/tailwind.config.ts
https://selleolabs.atlassian.net/browse/LC-233
This PR provides student app improvements according to designs
> student app ui-imporve

- apps/api/src/lessons/lessons.service.ts
- apps/api/src/questions/questions.service.ts
[https://selleolabs.atlassian.net/jira/software/projects/LC/boards/3?selectedIssue=LC-230](url)
This PR improves answering on questions and provides student answer in lesson show.
> feat: prepare api to return answers on questions

- apps/api/src/courses/courses.service.ts
- apps/api/src/courses/schemas/course.schema.ts
- apps/api/src/swagger/api-schema.json
[https://selleolabs.atlassian.net/jira/software/projects/LC/boards/3?selectedIssue=LC-217](url)
[https://selleolabs.atlassian.net/jira/software/projects/LC/boards/3?selectedIssue=LC-218](url)
This PR adds missing prop in endpoint and updates guard on lesson list in course.
> feat: add description to course list endpoint

- apps/web/app/components/ui/CategoryChip.tsx
- apps/web/app/modules/Courses/CourseView/CourseViewMainCard.tsx
- apps/web/app/modules/Dashboard/Courses/CourseCard.tsx
- apps/web/app/modules/Dashboard/Dashboard.page.tsx
- apps/web/app/modules/Dashboard/Settings/forms/ChangePasswordForm.tsx
- apps/web/app/modules/Dashboard/Settings/forms/UserForm.tsx
https://selleolabs.atlassian.net/browse/LC-227
This PR includes adjust to application designs
> feat:LC-227-adjust-design

- apps/web/app/components/ui/CategoryChip.tsx
- apps/web/app/components/ui/button.tsx
- apps/web/app/index.css
- apps/web/app/modules/Courses/CourseView/CourseViewMainCard.tsx
- apps/web/app/modules/Courses/CourseView/LessonsList.tsx
- apps/web/app/modules/Courses/Lesson/Lesson.page.tsx
- apps/web/app/modules/Courses/Lesson/LessonItems/Files.tsx
- apps/web/app/modules/Courses/Lesson/LessonItems/LessonItemsSwitch.tsx
- apps/web/app/modules/Courses/Lesson/LessonItems/Questions.tsx
- apps/web/app/modules/Courses/Lesson/LessonItems/TextBlock.tsx
- apps/web/app/modules/Courses/Lesson/Overview.tsx
- apps/web/app/modules/Courses/Lesson/Summary/index.tsx
- apps/web/app/modules/Dashboard/Courses/CourseCard.tsx
- apps/web/app/modules/Dashboard/Dashboard.page.tsx
- apps/web/app/modules/Dashboard/DashboardNavigation/DashboardNavigation.tsx
- apps/web/app/modules/Dashboard/DashboardNavigation/MenuItem.tsx
- apps/web/app/modules/Dashboard/DashboardNavigation/MenuItemLink.tsx
- apps/web/tailwind.config.ts
No realted JIRA issue
This PR consists of overall UI/UX app adjustments and improvements
> feat: overall UI/UX app adjustments

- apps/admin/package.json
- apps/admin/src/components/custom/Dashboard.tsx
- apps/admin/src/components/index.ts
- apps/admin/src/config/app.ts
https://selleolabs.atlassian.net/browse/LC-235
- changed the default AdminJS dashboard to users resource view
> feat: add Dashboard component for admin panel

- apps/web/app/api/generated-api.ts
- apps/web/app/modules/Courses/Lesson/Lesson.page.tsx
- apps/web/app/modules/Courses/Lesson/LessonItems/LessonItemsSwitch.tsx
- apps/web/app/modules/Courses/Lesson/LessonItems/Questions.tsx
- apps/web/app/modules/Courses/Lesson/types.ts
- apps/web/app/modules/Courses/Lesson/utils.ts
https://selleolabs.atlassian.net/browse/LC-229
it shows user answers
> requires api
> feat: LC-229 show user answers

- apps/web/app/modules/Courses/Lesson/LessonItems/LessonItemsSwitch.tsx
- apps/web/app/modules/Dashboard/Courses/CourseCard.tsx
- apps/web/app/modules/Dashboard/Dashboard.page.tsx
https://selleolabs.atlassian.net/browse/LC-237
It adds description to course card in courses list in dashboard.
> fix: LC-237 add description do dashboard course card

- apps/admin/src/adminResourceOptions/coursesOptions.ts
- apps/admin/src/adminResourceOptions/filesOptions.ts
- apps/admin/src/components/custom/CourseLessonsShow.tsx
- apps/admin/src/components/index.ts
- apps/admin/src/components/photo/PhotoPreview.tsx
- apps/admin/src/config/app.ts
- apps/admin/tsconfig.json
[https://selleolabs.atlassian.net/jira/software/projects/LC/boards/3?selectedIssue=LC-232](url)
This PR adds a custom component for assigning and deleting lessons to a course and adds a setup custom css file for deleting unnecessary elements (sub modal in archive modal).
> feat: add lessons component to course show

- apps/api/src/lessons/lessons.service.ts
- apps/api/src/questions/questions.service.ts
- apps/web/app/modules/Courses/Lesson/Lesson.page.tsx
- apps/web/app/modules/Courses/Lesson/LessonItems/LessonItemsSwitch.tsx
- apps/web/app/modules/Courses/Lesson/LessonItems/Questions.tsx
- apps/web/app/modules/Courses/Lesson/LessonItems/useQuestionQuery.ts
- apps/web/app/modules/Courses/Lesson/types.ts
- apps/web/app/modules/Courses/Lesson/utils.ts
https://selleolabs.atlassian.net/browse/LC-242
It allows user to save answers
> Fix lc 242 fix answering a questions

- apps/api/src/lessons/schemas/lessonItem.schema.ts
- apps/api/src/swagger/api-schema.json
- apps/web/app/api/generated-api.ts
- apps/web/app/modules/Courses/Lesson/LessonItems/Files.tsx
- apps/web/app/modules/Courses/Lesson/LessonItems/LessonItemStore.ts
- apps/web/app/modules/Courses/Lesson/LessonItems/LessonItemsSwitch.tsx
- apps/web/app/modules/Courses/Lesson/LessonItems/Presentation.tsx
- apps/web/app/modules/Courses/Lesson/LessonItems/Questions.tsx
- apps/web/app/modules/Courses/Lesson/LessonItems/Video.tsx
- apps/web/app/modules/Courses/Lesson/Summary/SingleLessonSummary.tsx
- apps/web/app/modules/Courses/Lesson/utils.ts
https://selleolabs.atlassian.net/browse/LC-288
- added lesson progress in the lesson summary
> feat: LC-228 lesson progress front

- apps/admin/src/components/photo/PhotoPreview.tsx
- apps/api/src/courses/courses.service.ts
[https://selleolabs.atlassian.net/jira/software/projects/LC/boards/3?selectedIssue=LC-238](url)
This PR provides a small change to the preview file in admin and in course lesson condition.
> fix: correct course lesson count and admin file preview

- apps/api/src/courses/courses.service.ts
- apps/api/src/nice-data-seeds.ts
- apps/api/src/seed-helpers.ts
- apps/web/app/modules/Courses/CourseView/CourseView.page.tsx
- apps/web/app/modules/Courses/Lesson/LessonItems/Questions.tsx
[LC-246](https://selleolabs.atlassian.net/browse/LC-246)
Resolved issues with the admin app view and updated production seed data.
https://github.com/user-attachments/assets/b60cfbb0-c00e-44a5-996f-284d3dd3ff45
[LC-246]: https://selleolabs.atlassian.net/browse/LC-246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: Production seeds adjustment

- apps/web/app/modules/Courses/Lesson/Breadcrumb.tsx
[LC-244](https://selleolabs.atlassian.net/browse/LC-244)
Changed Breadcrumb component position from `sticky` to `static`
[LC-244]: https://selleolabs.atlassian.net/browse/LC-244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: Change Breadcrumb component position to static

- apps/web/app/api/mutations/useMarkLessonItemAsCompleted.ts
- apps/web/app/modules/Courses/Lesson/LessonItems/LessonItemStore.ts
- apps/web/app/modules/Courses/Lesson/LessonItems/Presentation.tsx
- apps/web/app/modules/Courses/Lesson/LessonItems/Questions.tsx
- apps/web/app/modules/Courses/Lesson/LessonItems/Video.tsx
- fixed lesson progress bar 
https://github.com/user-attachments/assets/79061652-ec07-440c-83f9-5cafcfc57ecc
> fix: lesson progress bar

- apps/web/app/modules/Courses/Lesson/Lesson.page.tsx
- apps/web/app/modules/Courses/Lesson/LessonItems/LessonItemsSwitch.tsx
- apps/web/app/modules/Courses/Lesson/LessonItems/Questions.tsx
- apps/web/app/modules/Courses/Lesson/LessonItems/useQuestionQuery.ts
- apps/web/app/modules/Courses/Lesson/LessonItems/utils.ts
https://selleolabs.atlassian.net/browse/LC-247
- It sends answers on click with no useEffect(). 
- It adds default values for useStates for single and multiple answers
> useStates() are needed to allow user select just one answer for single select question or many answers for multi answer question
> Fix lc 247 send api request with no use effect

- apps/api/src/courses/courses.service.ts
- apps/api/src/courses/schemas/showCourseCommon.schema.ts
- apps/api/src/lessons/schemas/lesson.schema.ts
- apps/api/src/swagger/api-schema.json
- apps/web/app/api/generated-api.ts
- apps/web/app/modules/Courses/CourseView/CourseViewMainCard.tsx
- apps/web/app/modules/Courses/CourseView/LessonsList.tsx
- apps/web/app/modules/Courses/Lesson/Lesson.page.tsx
- apps/web/app/modules/Courses/Lesson/LessonItems/Files.tsx
https://selleolabs.atlassian.net/browse/LC-239
- added course progress data and course lessons data in course view
- added `Continue` functionality in course view
- added `Previous lesson` and `Next lesson` functionality in lesson view
> feat: LC-239 course progress

- apps/admin/src/components/custom/CourseLessonsShow.tsx
[LC-240](https://selleolabs.atlassian.net/browse/LC-240)
Enhanced the style of the CourseLessonsShow component.
Before:
After:
[LC-240]: https://selleolabs.atlassian.net/browse/LC-240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: CourseLessonsShow component appearance adjustment

- apps/admin/src/adminResourceOptions/lessonsOptions.ts
- apps/admin/src/components/custom/CourseLessonsShow.tsx
- apps/admin/src/components/custom/LessonContentItemsTable.tsx
- apps/admin/src/components/index.ts
- apps/admin/src/config/app.ts
[https://selleolabs.atlassian.net/jira/software/projects/LC/boards/3?selectedIssue=LC-206](url)
[https://selleolabs.atlassian.net/jira/software/projects/LC/boards/3?selectedIssue=LC-199](url)
This PR provides relation component for lesson to lesson items.
> feat: assign lesson item to lesson

- apps/web/app/modules/Courses/CourseView/CourseViewMainCard.tsx
- apps/web/app/modules/Courses/CourseView/LessonsList.tsx
- apps/web/package.json
- apps/web/tailwind.config.ts
- pnpm-lock.yaml
https://selleolabs.atlassian.net/browse/LC-250
- added custom thin scrollbar
> feat: add custom scrollbars

- apps/api/src/categories/categories.service.ts
- apps/api/src/courses/api/courses.controller.ts
- apps/api/src/courses/api/validations.ts
- apps/api/src/courses/courses.service.ts
[LC-221](https://selleolabs.atlassian.net/browse/LC-221)
Fixed the total item count returned by the course and category services. 
It ensures the count reflects the correct number of unique courses by using `countDistinct` and removes duplicates from joins.
Additionally, it checks that the course state is `published` and ensures that both the course and category are not archived.
[LC-221]: https://selleolabs.atlassian.net/browse/LC-221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Correct totalItem count in course and category services

- apps/web/app/api/mutations/useRegisterUser.ts
- apps/web/app/modules/Auth/Register.page.test.tsx
- apps/web/app/modules/Auth/Register.page.tsx
[LC-260](https://selleolabs.atlassian.net/browse/LC-260)
Added first name and last name fields with validation.
Updated `Register.page.test.tsx` to include tests for the new fields.
[LC-260]: https://selleolabs.atlassian.net/browse/LC-260?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Develop firstName and lastName fields

- apps/web/app/index.css
- apps/web/app/modules/Courses/CourseView/CourseViewMainCard.tsx
- apps/web/app/modules/Courses/CourseView/LessonsList.tsx
- apps/web/package.json
- apps/web/tailwind.config.ts
- pnpm-lock.yaml
[LC-250](https://selleolabs.atlassian.net/browse/LC-250)
Removed `tailwind-scrollbar` and developer custom once
[LC-250]: https://selleolabs.atlassian.net/browse/LC-250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Custom scrollbars

- apps/web/app/modules/Dashboard/Settings/Settings.layout.tsx
[LC-259](https://selleolabs.atlassian.net/browse/LC-259)
[LC-259]: https://selleolabs.atlassian.net/browse/LC-259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: Remove navigation from settings view

- apps/web/app/modules/Courses/CourseView/LessonsList.tsx
https://selleolabs.atlassian.net/browse/LC-270
- fixed the possibility to navigate to a lesson even if the user is not enrolled in the course
> fix: LC-270 lesson card in course view

- apps/admin/src/adminResourceOptions/categoriesOptions.ts
- apps/admin/src/adminResourceOptions/coursesOptions.ts
- apps/admin/src/adminResourceOptions/filesOptions.ts
- apps/admin/src/adminResourceOptions/lessonsOptions.ts
- apps/admin/src/adminResourceOptions/questionsOptions.ts
- apps/admin/src/adminResourceOptions/textBlocksOptions.ts
- apps/admin/src/adminResourceOptions/usersOptions.ts
[LC-251](https://selleolabs.atlassian.net/browse/LC-251)
Added icons to sidebar menu items
[LC-251]: https://selleolabs.atlassian.net/browse/LC-251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: update menu icon adminjs

- apps/admin/src/adminResourceOptions/common/actions/before/updateCourse.ts
- apps/admin/src/adminResourceOptions/coursesOptions.ts
- apps/api/src/courses/courses.service.ts
- apps/api/src/courses/schemas/course.schema.ts
- apps/api/src/courses/schemas/showCourseCommon.schema.ts
- apps/api/src/storage/migrations/0037_add_currency_column_to_courses_table.sql
- apps/api/src/storage/migrations/meta/0037_snapshot.json
- apps/api/src/storage/migrations/meta/_journal.json
- apps/api/src/storage/schema/index.ts
- apps/api/src/swagger/api-schema.json
- apps/web/app/api/generated-api.ts
- apps/web/app/lib/formatters/priceFormatter.ts
- apps/web/app/modules/Courses/CourseView/CourseViewMainCard.tsx
- apps/web/app/modules/Dashboard/Courses/CardCourseList.tsx
- apps/web/app/modules/Dashboard/Courses/CourseCard.tsx
- apps/web/app/modules/Dashboard/Courses/CourseCardButton.tsx
- apps/web/app/modules/Dashboard/Courses/TableCourseList.tsx
> feat: Add currency

- apps/web/app/modules/Dashboard/Dashboard.page.test.tsx
- apps/web/app/modules/Dashboard/Dashboard.page.tsx
- apps/web/app/utils/mocks/data/categories.ts
- apps/web/app/utils/mocks/data/courses.ts
- apps/web/app/utils/mocks/data/currentUser.ts
- apps/web/app/utils/mocks/handlers/auth.ts
- apps/web/app/utils/mocks/handlers/course.ts
- apps/web/app/utils/mocks/handlers/index.ts
- apps/web/app/utils/mocks/intersectionObserver.mock.ts
- apps/web/app/utils/mocks/matchMedia.mock.ts
- apps/web/app/utils/mocks/resizeObserver.mock.ts
- apps/web/app/utils/mocks/resolvers/withSearchParams.ts
- apps/web/vitest.config.ts
- apps/web/vitest.setup.ts
Added tests for the Dashboard page covering:
- rendering of course cards
- interaction with search input
- filtering courses by category
- sorting courses
- clearing search input and filters
- displaying an empty state when no courses match the filter criteria
> test: add tests for dashboard page

- apps/web/app/api/queries/index.ts
- apps/web/app/api/queries/useAvailableCourses.ts
- apps/web/app/api/queries/useCourse.ts
- apps/web/app/api/queries/useStudentCourses.ts
- apps/web/app/assets/svgs/hamburger-menu-close.svg
- apps/web/app/assets/svgs/hamburger-menu.svg
- apps/web/app/assets/svgs/index.ts
- apps/web/app/components/CourseProgress.tsx
- apps/web/app/hooks/useUserRole.ts
- apps/web/app/modules/Courses/CourseView/CourseView.page.tsx
- apps/web/app/modules/Courses/CourseView/CourseViewMainCard.tsx
- apps/web/app/modules/Courses/CourseView/LessonsList.tsx
- apps/web/app/modules/Courses/Lesson/Lesson.layout.tsx
- apps/web/app/modules/Courses/Lesson/Lesson.page.tsx
- apps/web/app/modules/Courses/Lesson/Overview.tsx
- apps/web/app/modules/Dashboard/Courses/CourseCard.tsx
- apps/web/app/modules/Dashboard/Courses/StudentCoursesCarousel.tsx
- apps/web/app/modules/Dashboard/Dashboard.layout.tsx
- apps/web/app/modules/Dashboard/Dashboard.page.tsx
- apps/web/app/modules/Dashboard/DashboardNavigation/DashboardNavigation.tsx
- apps/web/app/modules/common/SearchFilter/SearchFilter.tsx
- apps/web/tailwind.config.ts
[LC-279](https://selleolabs.atlassian.net/browse/LC-279)
https://github.com/user-attachments/assets/d7bae33c-835f-47f0-ac8c-be66d01b5613
[LC-279]: https://selleolabs.atlassian.net/browse/LC-279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Responsive layout for student views

- apps/api/src/common/decorators/roles.decorator.ts
- apps/api/src/common/guards/roles.guard.ts
- apps/api/src/courses/api/courses.controller.ts
- apps/api/src/lessons/api/lessons.controller.ts
- apps/api/src/users/api/users.controller.ts
- apps/web/app/api/generated-api.ts
- This pull request introduces role-based access endpoints to the project.
> feat: role based access endpoints

- apps/web/app/modules/Courses/Lesson/Summary/index.tsx
> fix: lesson summary styles

- apps/api/src/nice-data-seeds.ts
- apps/api/src/seed-helpers.ts
- apps/web/app/modules/Admin/LessonItems/CreateNewQuestion.tsx
- apps/web/app/modules/Admin/Lessons/CreateNewLesson.tsx
- apps/web/app/modules/Admin/Lessons/LessonItemsAssigner/LessonItemAssigner.tsx
- apps/web/app/modules/Dashboard/Courses/CourseCard.tsx
[LC-292](https://selleolabs.atlassian.net/browse/LC-292)
https://github.com/user-attachments/assets/17381755-a05f-4e5e-8b1f-f2e888e1c8df
[LC-292]: https://selleolabs.atlassian.net/browse/LC-292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Batch of improvements

- apps/api/src/lessons/lessons.service.ts
- apps/api/src/questions/questions.service.ts
- apps/api/src/questions/schema/questionsSchema.ts
- apps/web/app/modules/Courses/Lesson/LessonItems/FillInTheBlanks/FillInTheBlanks.tsx
- apps/web/app/modules/Courses/Lesson/LessonItems/FillInTheBlanks/dnd/DndBlank.tsx
- apps/web/app/modules/Courses/Lesson/LessonItems/FillInTheBlanks/dnd/DraggableWord.tsx
- apps/web/app/modules/Courses/Lesson/LessonItems/FillInTheBlanks/dnd/FillInTheBlanksDnd.tsx
- apps/web/app/modules/Courses/Lesson/LessonItems/FillInTheBlanks/dnd/SentenceBuilder.tsx
- apps/web/app/modules/Courses/Lesson/LessonItems/FillInTheBlanks/dnd/WordBank.tsx
- apps/web/app/modules/Courses/Lesson/LessonItems/FillInTheBlanks/dnd/index.ts
- apps/web/app/modules/Courses/Lesson/LessonItems/FillInTheBlanks/dnd/types.ts
- apps/web/app/modules/Courses/Lesson/LessonItems/Questions.tsx
- apps/web/app/modules/Courses/Lesson/Summary/index.tsx
[LC-294](https://selleolabs.atlassian.net/browse/LC-294)
https://github.com/user-attachments/assets/c4d7e7db-4e48-45d1-ad55-6a2aa20d9d70
[LC-294]: https://selleolabs.atlassian.net/browse/LC-294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Fill In The Blanks - dnd

- apps/api/src/lessons/api/lessons.controller.ts
- apps/api/src/lessons/lessonItems.service.ts
- apps/api/src/swagger/api-schema.json
- apps/web/app/api/generated-api.ts
- apps/web/app/api/mutations/admin/useUpdateQuestionOptions.ts
- apps/web/app/api/queries/admin/useQuestionOptions.ts
- apps/web/app/modules/Admin/Courses/Course.page.tsx
- apps/web/app/modules/Admin/Courses/Courses.page.tsx
- apps/web/app/modules/Admin/LessonItems/CreateNewQuestion.tsx
- apps/web/app/modules/Admin/LessonItems/LessonItem.page.tsx
- apps/web/app/modules/Admin/LessonItems/QuestionItem.tsx
- apps/web/app/modules/Admin/LessonItems/TextBlockItem.tsx
- apps/web/app/modules/Admin/LessonItems/question/AnswerOptions.tsx
- apps/web/app/modules/Admin/LessonItems/question/QuestionField.tsx
- apps/web/app/modules/Admin/LessonItems/question/SortableAnswerOption.tsx
- apps/web/app/modules/Admin/LessonItems/question/types.ts
- apps/web/app/modules/Admin/Lessons/CreateNewLesson.tsx
- apps/web/app/modules/Admin/Users/CreateNewUser.tsx
- apps/web/app/modules/Admin/Users/User.page.tsx
- apps/web/app/modules/Courses/Lesson/LessonItems/Files.tsx
- apps/web/app/modules/Courses/Lesson/LessonItems/Questions.tsx
- apps/web/app/modules/Courses/Lesson/LessonItems/Video.tsx
- apps/web/app/modules/stripe/PaymentForm.tsx
- added possibility to assign and edit question options
- quickfix: added support for external videos on frontend
> feat: question item options

- .github/workflows/deploy-api-production.yml
- .github/workflows/deploy-webapp-production.yml
This PR changes trigger on app production.
> chore: change deploy production trigger

- .github/workflows/deploy-api-production.yml
- .github/workflows/deploy-webapp-production.yml
This PR removes paths from deploy rules.
> chore: update deploy production path

- apps/api/src/lessons/lessons.service.ts
- apps/api/src/nice-data-seeds.ts
- apps/api/src/seed-helpers.ts
> refactor: Update seeds related to quiz and fill in the blanks

- apps/api/src/lessons/adminLessonItems.service.ts
- apps/api/src/lessons/adminLessons.service.ts
- apps/api/src/lessons/api/lessons.controller.ts
- apps/api/src/lessons/const/lessonItems.const.ts
- apps/api/src/lessons/lessonItems.type.ts
- apps/api/src/lessons/lessons.module.ts
- apps/api/src/lessons/repositories/adminLessonItems.repository.ts
- apps/api/src/lessons/repositories/adminLessons.repository.ts
- apps/api/src/lessons/schemas/lessonItem.schema.ts
[https://selleolabs.atlassian.net/jira/software/projects/LC/boards/3?selectedIssue=LC-297](url)
This PR allows you to pre-block edit lessons, questions and question answer options from being edited if answers have already been given.
> feat: blocking editing of lessons and questions with answers

- apps/web/app/modules/Courses/Lesson/LessonItems/FillInTheBlanks/TextBlank.tsx
https://selleolabs.atlassian.net/browse/LC-317
- changed the color of text in blank field
> style: improve visibility and update conditional classes for TextBlank component

- apps/web/app/modules/Courses/Lesson/LessonItems/FillInTheBlanks/dnd/DraggableWord.tsx
- apps/web/app/modules/Courses/Lesson/LessonItems/FillInTheBlanks/dnd/FillInTheBlanksDnd.tsx
https://selleolabs.atlassian.net/browse/LC-315
- disabled drag and drop in quiz fill in the blanks question
https://github.com/user-attachments/assets/a9f2f72b-dbe9-417d-84b4-f9ac29a6547e
> feat: disable dnd on completed quiz

- apps/web/app/components/RichText/toolbar/EditorToolbar.tsx
[LC-325](https://selleolabs.atlassian.net/browse/LC-325)
https://github.com/user-attachments/assets/c406b281-ded4-4d03-931e-76bf8d992b8b
[LC-325]: https://selleolabs.atlassian.net/browse/LC-325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Add fill in the blanks word template option to EditorToolbar

- apps/api/src/courses/courses.service.ts
- apps/api/src/lessons/api/lessons.controller.ts
- apps/api/src/lessons/lessons.service.ts
- apps/api/src/lessons/schemas/lesson.schema.ts
- apps/api/src/lessons/schemas/lesson.types.ts
- apps/api/src/lessons/schemas/lessonFileType.ts
- apps/api/src/lessons/schemas/lessonItem.schema.ts
- apps/api/src/swagger/api-schema.json
- apps/web/app/api/generated-api.ts
- apps/web/app/api/queries/admin/useQuestionOptions.ts
- apps/web/app/components/CourseProgress.tsx
- apps/web/app/modules/Admin/LessonItems/QuestionItem.tsx
- apps/web/app/modules/Admin/LessonItems/question/AnswerOptions.tsx
- apps/web/app/modules/Admin/LessonItems/question/QuestionField.tsx
- apps/web/app/modules/Courses/CourseView/LessonCard.tsx
- apps/web/app/modules/Courses/Lesson/LessonItems/FillInTheBlanks/FillInTheBlanks.tsx
- apps/web/app/modules/Courses/Lesson/LessonItems/FillInTheBlanks/dnd/FillInTheBlanksDnd.tsx
- apps/web/app/modules/Courses/Lesson/LessonItems/Question/Question.tsx
- apps/web/app/modules/Courses/Lesson/LessonItems/Question/SelectAnswer/SelectAnswer.tsx
- apps/web/app/modules/Courses/Lesson/LessonItems/Question/SelectAnswer/SelectAnswerOption.tsx
- apps/web/app/modules/Courses/Lesson/LessonItems/Question/SelectAnswer/SelectAnswerOptionQuiz.tsx
- apps/web/app/modules/Courses/Lesson/Overview.tsx
- apps/web/app/modules/Dashboard/Courses/StudentCoursesCarousel.tsx
[LC-316](https://selleolabs.atlassian.net/browse/LC-316), [LC-320](https://selleolabs.atlassian.net/browse/LC-320), [LC-312](https://selleolabs.atlassian.net/browse/LC-312)
[LC-316]: https://selleolabs.atlassian.net/browse/LC-316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-320]: https://selleolabs.atlassian.net/browse/LC-320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-312]: https://selleolabs.atlassian.net/browse/LC-312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Show correct answer as a full text with bold keywords

- .github/workflows/deploy-api-staging.yml
> chore: add missing seed path

- .github/workflows/deploy-api-staging.yml
- apps/api/package.json
- apps/api/src/nice-data-seeds.ts
- apps/api/src/seed-helpers.ts
- apps/api/src/seed.production.ts
- apps/api/src/seed.ts
- apps/api/src/truncateTables.ts
> chore: deploy update

- .github/workflows/deploy-api-production.yml
- apps/api/entrypoint.sh
- apps/api/package.json
This PR remove seed file for production.
> chore: update deploy production config

- apps/api/src/storage/migrations/0007_create_user_details.sql
- apps/api/src/storage/migrations/meta/0007_snapshot.json
- apps/api/src/storage/migrations/meta/_journal.json
- apps/api/src/storage/schema/index.ts
- apps/api/src/users/api/users.controller.ts
- apps/api/src/users/schemas/user.schema.ts
- apps/api/src/users/users.service.ts
[https://selleolabs.atlassian.net/jira/software/projects/LC/boards/3?selectedIssue=LC-331](url)
This PR adds user details for tutor page.
> feat: add user details endpoint

- apps/web/app/modules/Courses/Lesson/LessonItems/Question/SelectAnswer/SelectAnswerOptionQuiz.tsx
- apps/web/app/modules/Dashboard/Courses/CardCourseList.tsx
- apps/web/app/modules/Dashboard/Dashboard.page.tsx
[LC-342](https://selleolabs.atlassian.net/browse/LC-342), [LC-339](https://selleolabs.atlassian.net/browse/LC-339), [LC-341](https://selleolabs.atlassian.net/browse/LC-341)
[LC-342]: https://selleolabs.atlassian.net/browse/LC-342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-339]: https://selleolabs.atlassian.net/browse/LC-339?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-341]: https://selleolabs.atlassian.net/browse/LC-341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: Quiz and dashboard appearance adjustments

- apps/api/src/lessons/adminLessonItems.service.ts
- apps/api/src/lessons/repositories/adminLessonItems.repository.ts
- apps/api/src/swagger/api-schema.json
- apps/web/app/api/generated-api.ts
https://selleolabs.atlassian.net/browse/LC-343
- Fixed a bug that caused question options to not save when creating/updating.
> fix: saving options for the question

- apps/api/src/auth/api/auth.controller.ts
- apps/api/src/categories/api/categories.controller.ts
- apps/api/src/courses/api/courses.controller.ts
- apps/api/src/lessons/api/lessons.controller.ts
- apps/api/src/questions/api/questions.controller.ts
- apps/api/src/stripe/api/stripe.controller.ts
- apps/api/src/studentCompletedLessonItem/api/studentCompletedLessonItems.controller.ts
- apps/api/src/swagger/api-schema.json
- apps/api/src/users/__tests__/user.controller.e2e-spec.ts
- apps/api/src/users/api/users.controller.ts
- apps/api/test/factory/user.factory.ts
- apps/web/app/api/generated-api.ts
[https://selleolabs.atlassian.net/jira/software/projects/LC/boards/3?selectedIssue=LC-329](url)
This PR adds missing rolesGuard in Controllers.
> feat: check roles guard on endpoints

- README.md
- apps/api/.env.example
<div align="center">
[![MIT License](https://img.shields.io/badge/License-MIT-green.svg)](https://choosealicense.com/licenses/mit/) [![Node.js](https://img.shields.io/badge/Node.js-20.15.0-brightgreen.svg)](https://nodejs.org/) [![pnpm](https://img.shields.io/badge/pnpm-supported-blue.svg)](https://pnpm.io/) [![NestJS](https://img.shields.io/badge/NestJS-10.x-red.svg)](https://nestjs.com/) [![Remix](https://img.shields.io/badge/Remix-Latest-purple.svg)](https://remix.run/) [![PRs Welcome](https://img.shields.io/badge/PRs-welcome-brightgreen.svg)](http://makeapullrequest.com)
A modern, scalable Learning Management System built with cutting-edge technologies.
[Features](#features) • [Getting Started](#getting-started) • [Development](#development) • [Contributing](#contributing)
</div> …
> chore: update readme

- apps/api/src/lessons/lessons.service.ts
- apps/api/src/lessons/repositories/lessons.repository.ts
- apps/web/app/modules/Courses/Lesson/LessonItems/Question/Question.tsx
- apps/web/app/modules/Courses/Lesson/QuizSummaryModal.tsx
- apps/web/app/modules/Dashboard/Dashboard.page.tsx
This PR fixes problem with evaluation of quiz.
- Simplified `getFillInTheBlanksDndAnswers` logic to ensure that all answers are displayed properly
- Aligned `QuizSummaryModal` appearance with figma design.
- Fixed quiz evaluation problem
> fix: missing courseId in method

- README.md
- apps/api/src/auth/api/auth.controller.ts
- apps/api/src/categories/api/categories.controller.ts
- apps/api/src/courses/api/courses.controller.ts
- apps/api/src/seed.ts
- apps/api/src/studentCompletedLessonItem/api/studentCompletedLessonItems.controller.ts
- apps/api/src/swagger/api-schema.json
- apps/api/src/users/__tests__/user.controller.e2e-spec.ts
- apps/api/src/users/api/users.controller.ts
- apps/api/src/users/schemas/update-user.schema.ts
- apps/api/src/users/users.service.ts
- apps/web/app/api/generated-api.ts
- apps/web/app/api/mutations/index.ts
- apps/web/app/api/mutations/useUpsertUserDetails.ts
- apps/web/app/api/queries/useUserDetails.ts
- apps/web/app/modules/Dashboard/Settings/Settings.page.tsx
- apps/web/app/modules/Dashboard/Settings/forms/UserDetailsForm.tsx
[https://selleolabs.atlassian.net/jira/software/projects/LC/boards/3?selectedIssue=LC-344](url)
This PR adds bio for tutor and admin.
> feat: update teachers bio

- apps/api/src/courses/courses.service.ts
- apps/api/src/courses/schemas/showCourseCommon.schema.ts
- apps/api/src/courses/schemas/updateCourse.schema.ts
- apps/api/src/file/api/s3.controller.ts
- apps/api/src/file/s3.service.ts
- apps/api/src/swagger/api-schema.json
- apps/web/app/api/generated-api.ts
- apps/web/app/api/mutations/admin/useDeleteFile.ts
- apps/web/app/modules/Admin/Courses/Course.page.tsx
- apps/web/app/modules/Admin/Courses/CreateNewCourse.page.tsx
- apps/web/app/modules/Admin/Lessons/CreateNewLesson.page.tsx
- apps/web/app/modules/Admin/Lessons/Lesson.page.tsx
https://selleolabs.atlassian.net/browse/LC-346
- added image display while creating new course
- added image display while creating new lesson
- added possibility to edit image in course view
- added possibility to edit image in lesson view
- added endpoint for removing files from s3
> fix: LC-346 course/lesson image display

- .prettierignore
- apps/web/e2e/auth.setup.ts
- apps/web/e2e/fixture/auth.fixture.ts
- apps/web/e2e/tests/get-course.spec.ts
- apps/web/e2e/tests/login.spec.ts
- apps/web/e2e/tests/register.spec.ts
- apps/web/playwright.config.ts
- added login/logout playwright fixture
> feat: implement LoginFixture for streamlined login/logout in e2e tests

- apps/web/e2e/tests/course.spec.ts
- Fixed an issue in the quiz test where options were clicked too quickly without checking.
> fix: enhance quiz answer checks in e2e tests to verify input state and visibility of missing answers

- apps/web/app/modules/Statistics/Statistics.page.tsx
- apps/web/app/modules/Statistics/components/AvgPercentScoreChart.tsx
- apps/web/app/modules/Statistics/components/ContinueLearningCard.tsx
- apps/web/app/modules/Statistics/components/ProfileWithCalendar.tsx
- apps/web/app/modules/Statistics/components/RatesChart.tsx
> fix: simplify layout in Statistics components

- apps/api/src/lessons/lessons.service.ts
- apps/api/src/lessons/repositories/lessons.repository.ts
- apps/api/src/seed-helpers.ts
- apps/api/src/statistics/handlers/statistics.handler.ts
- apps/api/src/statistics/repositories/statistics.repository.ts
- apps/api/src/statistics/statistics.service.ts
This PR adds outstanding fixes from PR user statistics.
> feat: change string variables to constants

- apps/web/app/modules/Admin/Admin.layout.tsx
- apps/web/app/modules/Admin/EditCourse/EditCourse.tsx
- apps/web/app/modules/Admin/EditCourse/compontents/NavigationTabs.tsx
https://selleolabs.atlassian.net/browse/LC-401
Remove the sidebar from the splashscreen view when adding a course
> fix: remove sidebar from splashscreen

- apps/api/src/courses/courses.module.ts
- apps/api/src/courses/courses.service.ts
- apps/api/src/lessons/repositories/lessons.repository.ts
- apps/api/src/questions/questions.module.ts
- apps/api/src/questions/questions.service.ts
- apps/api/src/statistics/repositories/statistics.repository.ts
- apps/api/src/statistics/schemas/userStats.schema.ts
- apps/api/src/statistics/statistics.cron.ts
- apps/api/src/statistics/statistics.module.ts
- apps/api/src/statistics/statistics.service.ts
- apps/api/src/storage/migrations/0013_create_courses_summary_stats_table.sql
- apps/api/src/storage/migrations/0014_create_course_students_stats_table.sql
- apps/api/src/storage/migrations/meta/0013_snapshot.json
- apps/api/src/storage/migrations/meta/0014_snapshot.json
- apps/api/src/storage/migrations/meta/_journal.json
- apps/api/src/storage/schema/index.ts
- apps/api/src/stripe/stripe.module.ts
- apps/api/src/stripe/stripe.service.ts
- apps/api/src/stripe/stripeWebhook.handler.ts
- apps/api/src/studentCompletedLessonItem/studentCompletedLessonItems.module.ts
- apps/api/src/studentCompletedLessonItem/studentCompletedLessonItems.service.ts
- apps/api/src/swagger/api-schema.json
- apps/web/app/api/generated-api.ts
[418](https://selleolabs.atlassian.net/jira/software/projects/LC/boards/3?selectedIssue=LC-418)
[419](https://selleolabs.atlassian.net/jira/software/projects/LC/boards/3?selectedIssue=LC-419)
[420](https://selleolabs.atlassian.net/jira/software/projects/LC/boards/3?selectedIssue=LC-420)
This PR adds 3 metrics for teacher statistics:
- add conversion after freemium
- enrollments statistics
- average quiz score statistics
> feat: batch of teacher statistics

- apps/web/app/modules/Statistics/Admin/AdminStatistics.tsx
- apps/web/app/modules/Statistics/Admin/components/CourseCompletionPercentageChart.tsx
- apps/web/app/modules/Statistics/Admin/components/index.ts
[LC-411](https://selleolabs.atlassian.net/browse/LC-411)
[LC-411]: https://selleolabs.atlassian.net/browse/LC-411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Course completion chart

- apps/web/app/modules/Statistics/Admin/AdminStatistics.tsx
- apps/web/app/modules/Statistics/Admin/components/ConversionsAfterFreemiumLessonChart.tsx
- apps/web/app/modules/Statistics/Admin/components/FiveMostPopularCoursesChart.tsx
[LC-412](https://selleolabs.atlassian.net/browse/LC-412)
[LC-412]: https://selleolabs.atlassian.net/browse/LC-412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Conversions after freemium lesson chart

- apps/api/src/statistics/repositories/statistics.repository.ts
- apps/web/app/modules/Statistics/Admin/AdminStatistics.tsx
- apps/web/app/modules/Statistics/Admin/components/AvgScoreAcrossAllQuizzessChart.tsx
[LC-414](https://selleolabs.atlassian.net/browse/LC-414)
[LC-414]: https://selleolabs.atlassian.net/browse/LC-414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Average score across all quizzes chart

- apps/web/app/components/Navigation/Navigation.tsx
- apps/web/app/components/Navigation/NavigationFooter.tsx
- apps/web/app/components/Navigation/NavigationMenu.tsx
- apps/web/app/components/Navigation/NavigationMenuItem.tsx
- apps/web/app/modules/Admin/Admin.layout.tsx
- apps/web/app/modules/Statistics/Admin/AdminStatistics.tsx
- apps/web/app/modules/Statistics/Admin/components/AvgScoreAcrossAllQuizzessChart.tsx
- apps/web/app/modules/Statistics/Admin/components/EnrollmentChart.tsx
- apps/web/app/modules/Statistics/Admin/components/FiveMostPopularCoursesChart.tsx
[LC-413](https://selleolabs.atlassian.net/browse/LC-413)
[LC-413]: https://selleolabs.atlassian.net/browse/LC-413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Enrollment Chart

- apps/api/src/seed.ts
- apps/web/app/components/Navigation/NavigationFooter.tsx
- apps/web/app/config/routeAccessConfig.ts
- apps/web/app/modules/Admin/Users/Users.page.tsx
- apps/web/app/modules/Courses/CourseView/CourseViewMainCard.tsx
- apps/web/app/modules/Teacher/Teacher.page.tsx
- apps/web/app/modules/Teacher/TeacherPageBreadcrumbs.tsx
- apps/web/routes.ts
[LC-437](https://selleolabs.atlassian.net/browse/LC-437)
https://github.com/user-attachments/assets/c2ad9724-2613-45a8-a941-aeb6860bbe48
[LC-437]: https://selleolabs.atlassian.net/browse/LC-437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Link to teacher profile

- apps/web/app/modules/Courses/Lesson/Lesson.page.tsx
- apps/web/app/modules/Courses/Lesson/Summary/QuizSummary.tsx
[LC-424](https://selleolabs.atlassian.net/browse/LC-424)
https://github.com/user-attachments/assets/30c1bb2a-3f94-412f-8afc-c078cffa81c0
[LC-424]: https://selleolabs.atlassian.net/browse/LC-424?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: "You haven't finished course" visible after course completion

- apps/api/src/chapter/adminChapter.service.ts
- apps/api/src/chapter/chapter.controller.ts
- apps/api/src/chapter/repositories/adminChapter.repository.ts
- apps/api/src/lesson/adminLesson.repository.ts
- apps/api/src/lesson/adminLesson.service.ts
- apps/api/src/lesson/lesson.controller.ts
- apps/api/src/swagger/api-schema.json
- apps/web/app/api/generated-api.ts
- apps/web/app/api/mutations/admin/useDeleteChapter.ts
- apps/web/app/api/mutations/admin/useDeleteLesson.ts
This PR adds delete for chapter and lesson.
> feat: add delete option for chapter and lesson

- apps/web/app/api/mutations/admin/useUploadScormPackage.ts
- apps/web/app/modules/Admin/Scorm/components/CourseDetailsStep.tsx
- apps/web/app/modules/Admin/Scorm/components/PricingStep.tsx
- apps/web/app/modules/Admin/Scorm/components/StatusStep.tsx
- apps/web/app/modules/Admin/Scorm/scorm.config.tsx
- apps/web/app/modules/Dashboard/Courses/CourseCard.tsx
https://selleolabs.atlassian.net/browse/LC-480
- connected scrom flow with backend
> feat: connect create scorm form with be

- .github/workflows/deploy-api-staging.yml
- apps/api/entrypoint.sh
> fix: deployment

- apps/web/app/assets/svgs/index.ts
- Added missing checkmark icon
> fix: add missing icon

- apps/web/app/assets/svgs/index.ts
- Added missing exports to svgs
> refactor: Add missing exports to svgs

- apps/api/src/seed/seed-helpers.ts
[LC-]()
This PR fixes chapter display order.
> fix: chapter display order

- apps/api/src/courses/course.controller.ts
- apps/api/src/courses/validations/validations.ts
- apps/api/src/swagger/api-schema.json
- apps/web/app/api/generated-api.ts
- Added new validation for `get-student-courses` endpoint
> fix: Get Student Courses endpoint

- apps/reverse-proxy/Caddyfile
[LC-]()
This PR updates caddy proxy setup.
> fix: caddy proxy update

- apps/api/src/auth/__tests__/auth.controller.e2e-spec.ts
- apps/api/src/auth/auth.controller.ts
- apps/api/src/lesson/repositories/adminLesson.repository.ts
- apps/api/src/lesson/services/adminLesson.service.ts
- apps/api/src/user/__tests__/user.controller.e2e-spec.ts
- apps/api/test/helpers/test-helpers.ts
- apps/web/app/modules/Courses/NewCourseView/CourseChapter.tsx
[LC-521](https://selleolabs.atlassian.net/browse/LC-521)
- removed play chapter button
- added a bit of code formatting 
[LC-521]: https://selleolabs.atlassian.net/browse/LC-521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: remove play button from CourseChapter component

- apps/web/app/modules/Courses/NewCourseView/CourseViewSidebar/CourseProgress.tsx
[LC-522](https://selleolabs.atlassian.net/browse/LC-522)
- continue learning button now navigates to the first not started lesson
[LC-522]: https://selleolabs.atlassian.net/browse/LC-522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: implement navigation to first not started lesson in CourseProgress component

- apps/web/app/modules/Courses/NewCourseView/CourseChapterLesson.tsx
[LC-526](https://selleolabs.atlassian.net/browse/LC-526)
- removed link from chapter lesson in chapter view
[LC-526]: https://selleolabs.atlassian.net/browse/LC-526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: update CourseChapterLesson to use div instead of Link

- apps/api/src/courses/course.service.ts
- apps/api/src/events/course/course-activity.event.ts
- apps/api/src/events/lesson/lesson-completed.event.ts
- apps/api/src/events/quiz/quiz-completed.event.ts
- apps/api/src/events/user/user-activity.event.ts
- apps/api/src/lesson/repositories/lesson.repository.ts
- apps/api/src/statistics/handlers/statistics.handler.ts
- apps/api/src/statistics/repositories/statistics.repository.ts
- apps/api/src/statistics/statistics.controller.ts
- apps/api/src/statistics/statistics.cron.ts
- apps/api/src/statistics/statistics.service.ts
- apps/api/src/storage/migrations/0009_add_not_null_chapter_id_in_student_lesson_progress.sql
- apps/api/src/storage/migrations/meta/0009_snapshot.json
- apps/api/src/storage/migrations/meta/_journal.json
- apps/api/src/storage/schema/index.ts
- apps/api/src/swagger/api-schema.json
- apps/web/app/api/generated-api.ts
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/QuizLessonForm.tsx
[LC-512](https://selleolabs.atlassian.net/jira/software/projects/LC/boards/3?selectedIssue=LC-512)
This PR updates missing methods in statistics module.
[LC-512]: https://selleolabs.atlassian.net/browse/LC-512?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: update statistics module

- apps/web/app/modules/Courses/Lesson/LessonContent.tsx
- apps/web/app/modules/Courses/NewCourseView/CourseViewSidebar/CourseProgress.tsx
[LC-524](https://selleolabs.atlassian.net/browse/LC-524)
- removed `continue` button from lesson view and moved its logic into handleNext lesson
[LC-524]: https://selleolabs.atlassian.net/browse/LC-524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: change lesson content navigation

- apps/web/app/modules/Admin/EditCourse/CourseLessons/CourseLessons.helpers.ts
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/QuizLessonForm.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/components/FillInTheBlanksQuestion.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/components/QuestionSelector.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/components/QuestionTitle.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/components/QuestionWrapper.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/components/ScaleQuestion.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/validators/quizLessonFormSchema.ts
https://selleolabs.atlassian.net/browse/LC-533
https://selleolabs.atlassian.net/browse/LC-532
https://selleolabs.atlassian.net/browse/LC-529
Open accordion after add new question 
Split fill in the blank into two separate in select
> fix: problem with accordion and remove unused select

- apps/web/app/api/queries/index.ts
- apps/web/app/components/Presentation/Presentation.tsx
- apps/web/app/modules/Courses/Lesson/LessonContent.tsx
- apps/web/app/modules/Dashboard/Courses/CourseList.tsx
[LC-454](https://selleolabs.atlassian.net/browse/LC-454)
- added support for google slides
[LC-454]: https://selleolabs.atlassian.net/browse/LC-454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add isExternalUrl prop to Presentation component for handling external presentations

- apps/api/src/chapter/adminChapter.service.ts
- apps/api/src/chapter/repositories/adminChapter.repository.ts
- apps/api/src/courses/course.controller.ts
- apps/api/src/courses/course.service.ts
- apps/api/src/courses/validations/validations.ts
- apps/api/src/lesson/lesson.module.ts
- apps/api/src/lesson/repositories/adminLesson.repository.ts
- apps/api/src/lesson/repositories/lesson.repository.ts
- apps/api/src/lesson/services/adminLesson.service.ts
- apps/api/src/lesson/services/lesson.service.ts
- apps/api/src/questions/question.service.ts
- apps/api/src/studentLessonProgress/studentLessonProgress.service.ts
- apps/api/src/swagger/api-schema.json
- apps/web/app/api/generated-api.ts
- apps/web/app/api/queries/useCourses.ts
[LC-511](https://selleolabs.atlassian.net/jira/software/projects/LC/boards/3?selectedIssue=LC-511)
This PR improves tracking of lesson and chapter progress.
[LC-511]: https://selleolabs.atlassian.net/browse/LC-511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: improve student progress

- .github/workflows/e2e.yml
- apps/web/app/api/api-client.ts
- apps/web/playwright.config.ts
> refactor: update API client and playwright config for testing mode

- apps/api/src/lesson/lesson.schema.ts
- apps/api/src/lesson/lesson.type.ts
- apps/api/src/lesson/services/lesson.service.ts
- apps/api/src/questions/question.repository.ts
- apps/api/src/questions/question.service.ts
- apps/api/src/questions/schema/question.types.ts
- apps/api/src/seed/e2e-data-seeds.ts
- apps/api/src/seed/nice-data-seeds.ts
- apps/api/src/studentLessonProgress/studentLessonProgress.service.ts
- apps/api/src/swagger/api-schema.json
- apps/web/app/api/generated-api.ts
[LC-549](https://selleolabs.atlassian.net/jira/software/projects/LC/boards/3?selectedIssue=LC-549)
This PR add batch of question answering improvements and adds nextLessonId and nextLessonChapterId to lesson show response.
[LC-549]: https://selleolabs.atlassian.net/browse/LC-549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Mw feat 548 quiz improvments

- apps/api/src/chapter/repositories/adminChapter.repository.ts
- apps/api/src/courses/course.service.ts
- apps/api/src/lesson/lesson.schema.ts
- apps/api/src/lesson/repositories/lesson.repository.ts
- apps/api/src/lesson/services/lesson.service.ts
- apps/api/src/scorm/services/scorm.service.ts
- apps/api/src/seed/e2e-data-seeds.ts
- apps/api/src/seed/nice-data-seeds.ts
- apps/api/src/seed/seed-helpers.ts
- apps/api/src/studentLessonProgress/studentLessonProgress.service.ts
- apps/api/src/swagger/api-schema.json
- apps/api/src/utils/types/test-types.ts
- apps/web/app/api/generated-api.ts
[LC-]()
This PR removes not needed field in show lesson response, updates seed and types to be valid with every question types.
> feat: update seed and remove nextLessonChapterId

- apps/api/src/seed/nice-data-seeds.ts
- apps/web/app/api/generated-api.ts
[LC-]()
This PR adds batch of improvements to seed setup.
> feat: update seed setup

- .github/workflows/e2e.yml
- apps/api/src/seed/nice-data-seeds.ts
- apps/web/app/context/LeaveModalContext.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/components/PhotoQuestion.tsx
This PR fixes web production deployment
> fix: repair test on web deployment

- .github/workflows/deploy-api-production.yml
- apps/api/entrypoint.sh
This PR is fix for seed on production.
> feat: add seed for production

- .github/workflows/deploy-api-production.yml
This PR fixes deploy of prdouction.
> chore: update secrets for seed on production

- apps/web/app/entry.client.tsx
- apps/web/app/modules/Courses/Lesson/Lesson.page.tsx
- apps/web/app/modules/Courses/Lesson/LessonContent.tsx
- apps/web/app/modules/Courses/Lesson/LessonSidebar.tsx
- apps/web/app/modules/Courses/Lesson/Quiz.tsx
- apps/web/app/modules/Global/Providers.tsx
- apps/web/package.json
- pnpm-lock.yaml
[LC-562](https://selleolabs.atlassian.net/browse/LC-562)
- Fixed a bug that caused lesson completion to not update the ToC.
- Fixed navigation to the next chapter when quiz is the last lesson.
- Fixed styles of ToC according to figma design
- Added react query devtool
[LC-562]: https://selleolabs.atlassian.net/browse/LC-562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: update lesson sidebar to use lessonId and fetch course data dynamically

- apps/web/app/components/ui/dropdown-menu.tsx
- apps/web/app/context/LeaveModalContext.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/components/PhotoQuestion.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/components/QuestionSelector.tsx
[LC-565](https://selleolabs.atlassian.net/jira/software/projects/LC/boards/3?selectedIssue=LC-565)
[LC-565]: https://selleolabs.atlassian.net/browse/LC-565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: fix appearance of dropdown questions

- .github/workflows/deploy-api-production.yml
- apps/api/entrypoint.sh
This PR adds setup for deployment workflow on production.
> chore: add seed setup for production

- apps/web/app/modules/Courses/Lesson/Question/FillInTheBlanks/dnd/FillInTheBlanksDnd.tsx
- apps/web/app/modules/Courses/Lesson/Question/FillInTheBlanks/dnd/WordBank.tsx
- apps/web/app/modules/Courses/Lesson/Question/TrueOrFalse.tsx
Fixed validation issues before submission.
Corrected a word in the fill-in-the-blanks word bank.
> refactor: Batch of fixes

- apps/web/app/components/FileUploadInput/ImageUploadInput.tsx
- apps/web/app/modules/Admin/AddCourse/AddCourse.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/hooks/useQuizLessonForm.tsx
- apps/web/app/modules/Admin/EditCourse/CourseSettings/CourseSettings.tsx
https://selleolabs.atlassian.net/jira/software/projects/LC/boards/3?selectedIssue=LC-555
Fix problem with reupload image on frontend and fix problem with add edit question
> fix: image reupload 

- apps/web/app/modules/Courses/Lesson/Lesson.page.tsx
[LC-563](https://selleolabs.atlassian.net/jira/software/projects/LC/boards/3?selectedIssue=LC-563)
[LC-563]: https://selleolabs.atlassian.net/browse/LC-563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Change chapter title

- apps/api/src/courses/course.service.ts
- apps/api/src/courses/schemas/showCourseCommon.schema.ts
- apps/api/src/swagger/api-schema.json
- apps/web/app/api/generated-api.ts
- apps/web/app/components/ui/textarea.tsx
- apps/web/app/locales/en/translation.json
- apps/web/app/modules/Admin/AddCourse/AddCourse.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/components/FillInTheBlanksQuestion.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/components/MatchWordsQuestion.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/components/PhotoQuestion.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/components/QuestionSelector.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/components/QuestionTitle.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/components/ScaleQuestion.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/TextLessonForm/TextLessonForm.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/components/ChaptersList.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/components/LessonCardList.tsx
- apps/web/app/modules/Admin/EditCourse/CoursePricing/hooks/useCoursePricingForm.ts
- apps/web/app/modules/Admin/EditCourse/CourseSettings/CourseSettings.tsx
https://selleolabs.atlassian.net/jira/software/projects/LC/boards/3?selectedIssue=LC-555
Fix problem with fileurl and fix textarea input
> fix: visual fixes

- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/QuizLessonForm.tsx
Fix accordion problem, when we change the lesson then the accordion opens for the new lesson and it shouldn't
> fix: accordion problem

- apps/api/src/file/file.service.ts
- apps/api/src/lesson/lesson.schema.ts
- apps/api/src/lesson/services/lesson.service.ts
- apps/api/src/questions/question.repository.ts
- apps/api/src/questions/question.service.ts
- apps/api/src/questions/schema/question.schema.ts
- apps/api/src/statistics/repositories/statistics.repository.ts
- apps/api/src/statistics/schemas/userStats.schema.ts
- apps/api/src/statistics/statistics.module.ts
- apps/api/src/statistics/statistics.service.ts
- apps/api/src/studentLessonProgress/studentLessonProgress.service.ts
- apps/api/src/swagger/api-schema.json
- apps/web/app/api/generated-api.ts
- apps/web/app/api/mutations/useSubmitQuiz.ts
- apps/web/app/assets/svgs/arrows/carret-right.svg
- apps/web/app/assets/svgs/arrows/index.ts
- apps/web/app/components/CourseProgress.tsx
- apps/web/app/locales/en/translation.json
- apps/web/app/locales/pl/translation.json
- apps/web/app/modules/Statistics/Client/ClientStatistics.tsx
- apps/web/app/modules/Statistics/Client/components/ChapterCard.tsx
- apps/web/app/modules/Statistics/Client/components/ContinueLearningCard.tsx
- packages/eslint-config/library.js
- packages/eslint-config/package.json
- pnpm-lock.yaml
[LC-530](https://selleolabs.atlassian.net/jira/software/projects/LC/boards/3?selectedIssue=LC-530)
This PR adds response for next lesson and structure change for quiz evaluation endpoint.
[LC-530]: https://selleolabs.atlassian.net/browse/LC-530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: next chapter interaction

- .github/workflows/deploy-api-production.yml
This PR removes seed from production deployment.
> chore: remove seed from production

- apps/web/app/locales/en/translation.json
- apps/web/app/locales/pl/translation.json
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/QuizLessonForm.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/components/QuestionWrapper.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/validators/quizLessonFormSchema.ts
- apps/web/app/modules/Admin/EditCourse/CoursePricing/CoursePricing.tsx
- apps/web/app/modules/Admin/EditCourse/CourseStatus/CourseStatus.tsx
- apps/web/app/modules/Admin/components/LeaveConfirmationModal.tsx
https://selleolabs.atlassian.net/browse/LC-573
Add border for not validated questions
Add modal text for not validated form while leaving
Style pricing and status in course admin view
> fix: add validation and styles consistent

- apps/api/src/chapter/repositories/adminChapter.repository.ts
- apps/api/src/lesson/repositories/adminLesson.repository.ts
- apps/api/src/lesson/services/adminLesson.service.ts
- apps/web/app/components/SortableList/SortableList.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/CourseLessons.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/QuizLessonForm.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/QuizLessonForm.types.ts
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/components/AnswerSelectQuestion.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/components/FillInTheBlanksQuestion.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/components/MatchWordsQuestion.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/components/PhotoQuestion.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/components/QuestionWrapper.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/components/ScaleQuestion.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/components/TrueOrFalseQuestion.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/hooks/useQuizLessonForm.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/validators/quizLessonFormSchema.ts
- apps/web/app/modules/Admin/EditCourse/CourseLessons/components/ChaptersList.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/components/LessonCardList.tsx
[LC-572](https://selleolabs.atlassian.net/jira/software/projects/LC/boards/3?selectedIssue=LC-572)
- `SortableList.tsx`: Improved type safety by making id fields mandatory and replaced interfaces with type aliases.
- `QuizLessonForm.tsx`: Reordered declarations and added temporary id to new options using `crypto.randomUUID()`.
- `QuizLessonForm.types.ts`: Made id mandatory in QuestionOption and Question types.
- Components: Updated several components to use id instead of displayOrder and added id to new options using `crypto.randomUUID()`.
[LC-572]: https://selleolabs.atlassian.net/browse/LC-572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Drag and drop reordering logic

- apps/api/src/auth/auth.service.ts
- apps/api/src/category/category.controller.ts
- apps/api/src/category/category.service.ts
- apps/api/src/chapter/adminChapter.service.ts
- apps/api/src/chapter/repositories/adminChapter.repository.ts
- apps/api/src/chapter/schemas/chapter.schema.ts
- apps/api/src/common/guards/roles.guard.ts
- apps/api/src/courses/course.controller.ts
- apps/api/src/courses/course.service.ts
- apps/api/src/courses/schemas/course.schema.ts
- apps/api/src/courses/validations/validations.ts
- apps/api/src/lesson/lesson.controller.ts
- apps/api/src/lesson/lesson.schema.ts
- apps/api/src/lesson/repositories/adminLesson.repository.ts
- apps/api/src/questions/question.repository.ts
- apps/api/src/seed/seed-helpers.ts
- apps/api/src/seed/seed-prod.ts
- apps/api/src/seed/seed.ts
- apps/api/src/seed/seed.types.ts
- apps/api/src/stripe/stripe.controller.ts
- apps/api/src/stripe/stripe.service.ts
- apps/api/src/swagger/api-schema.json
- apps/api/src/user/schemas/createUser.schema.ts
- apps/api/src/user/schemas/updateUser.schema.ts
- apps/api/src/user/schemas/userQuery.ts
- apps/api/src/user/user.controller.ts
- apps/api/src/user/user.service.ts
[LC-583](https://selleolabs.atlassian.net/jira/software/projects/LC/boards/3?selectedIssue=LC-583)
This PR fixes double progress bar in chapter progress and add type for all props with type string to `UUIDTYPE`.
[LC-583]: https://selleolabs.atlassian.net/browse/LC-583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: double progress bar

- apps/api/src/lesson/lesson.schema.ts
- apps/api/src/lesson/repositories/lesson.repository.ts
- apps/api/src/lesson/services/lesson.service.ts
- apps/api/src/seed/nice-data-seeds.ts
- apps/api/src/swagger/api-schema.json
- apps/web/app/api/generated-api.ts
- apps/web/app/modules/Courses/Lesson/LessonContent.tsx
- apps/web/app/modules/Courses/Lesson/Quiz.tsx
[LC-584]()https://selleolabs.atlassian.net/jira/software/projects/LC/boards/3?selectedIssue=LC-584
This PR improves isDisabled method for nest lesson button in lesson page.
[LC-584]: https://selleolabs.atlassian.net/browse/LC-584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: refactor next button disabled state

- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/QuizLessonForm.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/components/AnswerSelectQuestion.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/components/FillInTheBlanksQuestion.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/components/MatchWordsQuestion.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/components/PhotoQuestion.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/components/ScaleQuestion.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/components/TrueOrFalseQuestion.tsx
- apps/web/e2e/tests/createCourse.spec.ts
- apps/web/playwright.config.ts
https://selleolabs.atlassian.net/browse/LC-588
Add e2e test for adding questions in course creation module
> feat: add test for adding questions

- apps/web/e2e/tests/createCourse.spec.ts
Remove fill in the blank from e2e, because this causes the staging tests to fail
> fix: remove fill in the blank from e2e temporary

- apps/web/e2e/tests/createCourse.spec.ts
> fix: e2e course creation

- apps/web/e2e/tests/createCourse.spec.ts
Remove photo question temporary
> fix: remove photo question temporary

- apps/web/e2e/tests/admin/create-course.spec.ts
- apps/web/e2e/tests/admin/settings.spec.ts
- apps/web/e2e/tests/teacher/edit-course.spec.ts
https://selleolabs.atlassian.net/browse/LC-601
Add e2e test to check if admin can change settings. 
Add e2e test to check if teacher can edit course which occurs on his course list
> feat: add test for admin settings and teacher edit chapter

- apps/web/app/components/RichText/Editor.tsx
- apps/web/app/components/RichText/Viever.tsx
- apps/web/app/components/RichText/plugins.ts
- apps/web/app/components/RichText/styles.ts
- apps/web/app/components/RichText/toolbar/EditorToolbar.tsx
- apps/web/package.json
- pnpm-lock.yaml
[LC-600](https://selleolabs.atlassian.net/browse/LC-600)
- added support for checklist and nested list to the rich text editor/viewer
[LC-600]: https://selleolabs.atlassian.net/browse/LC-600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add checklist support in RichText editor and viewer components

- apps/api/package.json
- apps/api/src/seed/e2e-data-seeds.ts
- apps/reverse-proxy/package.json
- apps/web/app/components/Navigation/NavigationMenuItem.tsx
- apps/web/app/components/ui/select.tsx
- apps/web/e2e/tests/admin/categories.spec.ts
- apps/web/e2e/tests/student/student-navigation.spec.ts
- apps/web/e2e/tests/teacher/edit-course.spec.ts
- apps/web/i18n.ts
- apps/web/package.json
- apps/web/playwright.config.ts
- package.json
- turbo.json
[LC-570](https://selleolabs.atlassian.net/browse/LC-570)
- set language to en in test env
- set one worker for each test dir
> [!WARNING]
> if you want to run environment for e2e test locally you shod run `pnpm dev:test` then `pnpm test:web:e2e` in repo root
[LC-570]: https://selleolabs.atlassian.net/browse/LC-570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add dev:test scripts for API, and web, update E2E tests for better navigation and category verification

- apps/web/app/api/api-client.ts
- apps/web/app/api/mutations/useLogoutUser.ts
- apps/web/app/entry.client.tsx
- apps/web/app/modules/Global/Providers.tsx
- apps/web/app/root.tsx
- apps/web/i18n.ts
- fixed a bug that caused freeze of entire app
- fixed a bug with error flicker after logout
- fixed a bug that prevented password reminder emails from being sent
> fix: known app issues

- .github/workflows/deploy-learn-production.yml
> feat: Add sentry

- apps/web/app/locales/en/translation.json
- apps/web/app/locales/pl/translation.json
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/TextLessonForm/TextLessonForm.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/TextLessonForm/hooks/useTextLessonForm.ts
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/TextLessonForm/validators/useTextLessonFormSchema.ts
ISSUE-75 (redacted)
Add missing validation in Text lesson
> feat: add missing validation in text lesson

- apps/api/src/auth/auth.service.ts
- apps/api/src/file/file.service.ts
This PR changes the email address and removes the remnants of redis.
> fix: reset password and remove redis

- apps/api/src/main.ts
- apps/api/src/utils/environment-validation.ts
[LC-606]()
[LC-606]: https://selleolabs.atlassian.net/browse/LC-606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore_add_environment_variable_to_Sentry

- apps/api/src/auth/auth.controller.ts
- apps/web/app/api/api-client.ts
- apps/web/app/modules/Auth/authService.ts
[LC-607](https://selleolabs.atlassian.net/jira/software/projects/LC/boards/3?selectedIssue=LC-607)
[LC-607]: https://selleolabs.atlassian.net/browse/LC-607?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix_lc-607_auth_refresh_token

- README.md
Updating readme with more business-focused features description
> docs: update readme with improved features description

- apps/api/src/storage/migrations/0013_change_type_of_description_column_in_lessons.sql
- apps/api/src/storage/migrations/meta/0013_snapshot.json
- apps/api/src/storage/migrations/meta/_journal.json
- apps/api/src/storage/schema/index.ts
- apps/web/app/locales/en/translation.json
- apps/web/app/locales/pl/translation.json
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/TextLessonForm/TextLessonForm.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/TextLessonForm/validators/useTextLessonFormSchema.ts
Currently character limit in text editor (text lesson) is not enough, especially in case of special characters such as checkbox which takes 150 characters (to be fixed another time).
> chore: update translation and description column in lessons

- apps/api/src/app.module.ts
[LC-]()
Make stripe module optional
> chore(Stripe): make stripe module optional

- apps/api/src/courses/__tests__/course.controller.e2e-spec.ts
- apps/api/src/courses/course.controller.ts
- apps/api/src/courses/course.service.ts
- apps/api/src/courses/schemas/courseQuery.ts
- apps/api/src/courses/schemas/createCoursesEnrollment.ts
- apps/api/src/courses/schemas/enrolledStudent.schema.ts
- apps/api/src/courses/schemas/studentsById.ts
- apps/api/src/courses/validations/validations.ts
- apps/api/src/stripe/stripeWebhook.handler.ts
- apps/api/src/swagger/api-schema.json
[LC-634](https://selleolabs.atlassian.net/issues/LC-634?jql=ORDER%20BY%20created%20DESC)
- retrieve studentIds byt courseId
- create bulk courses enrolments 
[LC-634]: https://selleolabs.atlassian.net/browse/LC-634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LC-634 create bulk courses enrolments

- apps/api/src/category/category.controller.ts
- apps/api/src/category/category.service.ts
- apps/api/src/courses/course.controller.ts
- apps/api/src/courses/course.service.ts
- apps/api/src/swagger/api-schema.json
- apps/web/app/api/generated-api.ts
- apps/web/app/api/mutations/admin/useDeleteCategory.ts
- apps/web/app/api/mutations/admin/useDeleteCourse.ts
- apps/web/app/api/mutations/admin/useDeleteManyCategories.ts
- apps/web/app/api/mutations/admin/useDeleteManyCourses.ts
- apps/web/app/api/mutations/index.ts
- apps/web/app/locales/en/translation.json
- apps/web/app/locales/pl/translation.json
- apps/web/app/modules/Admin/Categories/Categories.page.tsx
- apps/web/app/modules/Admin/Courses/Courses.page.tsx
- apps/web/app/modules/Admin/EditCourse/EditCourse.types.ts
[LC-619](https://selleolabs.atlassian.net/browse/LC-619?atlOrigin=eyJpIjoiNjAzZjNhNjc2NGJhNDFiMmEyNzU4Y2M5MWU5NTZmMjgiLCJwIjoiaiJ9)
[LC-619]: https://selleolabs.atlassian.net/browse/LC-619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Mm lc 619 delete categories

- apps/web/app/api/mutations/useLoginUser.ts
[LC-641](https://selleolabs.atlassian.net/browse/LC-641)
[LC-641]: https://selleolabs.atlassian.net/browse/LC-641?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: add queryclient to mutation for nagivgating user correctly

- README.md
Updated `README.md` with currently available testing accounts, because it was outdated.
> docs(SCS): update README.md with current available accounts

- .github/pull_request_template.md
- apps/api/.eslintrc.js
- apps/api/src/swagger/api-schema.json
- apps/api/test/create-e2e-test.ts
- apps/api/test/create-unit-test.ts
- apps/api/test/jest-e2e-setup.ts
- apps/api/test/jest-e2e.json
- apps/api/test/test-database.ts
- apps/web/app/api/generated-api.ts
- apps/web/e2e/tests/admin/admin-navigation.spec.ts
- apps/web/e2e/tests/admin/settings.spec.ts
- apps/web/e2e/tests/content-creator/content-creator-navigation.spec.ts
- apps/web/e2e/tests/content-creator/settings.spec.ts
- apps/web/e2e/tests/student/student-navigation.spec.ts
- Update profile URL path from `/content-creators/[id]` to `/profile/[id]`
- Change navigation text from "Your courses" to "Available Courses"
- Fix tests to reflect new URL patterns and text changes:
- Admin navigation tests
- Content creator navigation tests
- Student navigation tests
- Settings tests
All navigation-related tests have been updated to match the new URL structure and text changes.
> fix: Update Profile URL and Navigation Text

- apps/web/app/modules/Courses/CourseView/CourseViewSidebar/CourseProgress.tsx
[SCS-490](https://github.com/Selleo/mentingo/issues/490)
Fixed the styling for the share button. Now it should correctly display the secondary styling, instead of primary.
> fix(SCS-490): fixed secondary styling for share button

- apps/web/app/locales/en/translation.json
- apps/web/app/locales/pl/translation.json
- apps/web/app/modules/Dashboard/Settings/Language/LanguageProvider.tsx
- apps/web/app/modules/Dashboard/Settings/Language/LanguageStore.ts
- apps/web/app/modules/Dashboard/Settings/Settings.page.tsx
- apps/web/app/modules/Dashboard/Settings/components/LanguageSelect.tsx
- apps/web/app/modules/Global/Providers.tsx
[SCS-462](https://github.com/Selleo/mentingo/issues/462)
Added the ability to change the UI language, selected language is persisted across sessions.
> feat(SCS-462): Implement ability to change UI language

- apps/web/app/locales/en/translation.json
Fixed translation key in `profile` page, that was accidentally changed in one of the last PR's
> fix(SCS): translation key in profile page

- apps/api/src/auth/__tests__/auth.controller.e2e-spec.ts
- apps/api/src/auth/auth.service.ts
- apps/web/app/modules/Courses/Lesson/Lesson.page.tsx
- apps/web/app/modules/Courses/Lesson/LessonContent.tsx
[LC-569](https://github.com/Selleo/mentingo/issues/569)
Improve lesson view responsive design 
[LC-569]: https://selleolabs.atlassian.net/browse/LC-569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(SCS-569): Improve lesson view responsive design

- apps/web/app/modules/Courses/Lesson/LessonContent.tsx
- apps/web/e2e/tests/student/course-workflow.spec.ts
[LC-492](https://github.com/Selleo/mentingo/issues/492)
The main issue was resolved with changes from https://github.com/Selleo/mentingo/pull/579. There is a fix after removing the text from the "Previous" and "Next" buttons in the lesson.
[LC-492]: https://selleolabs.atlassian.net/browse/LC-492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: student navigation through lessons e2e test fix

- apps/api/src/ai/__tests__/ai.repository.spec.ts
- apps/api/src/ai/__tests__/createAiMentorLesson.ts
- apps/api/src/ai/repositories/ai.repository.ts
- apps/api/src/ai/services/message.service.ts
- apps/api/src/ai/utils/ai.config.ts
- apps/api/src/auth/__tests__/auth.service.spec.ts
- apps/api/src/seed/nice-data-seeds.ts
- apps/api/src/seed/seed-helpers.ts
- apps/api/src/utils/types/test-types.ts
- apps/api/test/factory/category.factory.ts
- apps/api/test/factory/chapter.factory.ts
- apps/api/test/factory/course.factory.ts
- apps/web/app/modules/Courses/Lesson/AiMentorLesson/AiMentorLesson.tsx
[SCS-573](https://github.com/Selleo/mentingo/issues/573)
- Added **15 test cases** for the **AI Repository** to enhance test coverage and ensure reliability.
- Created `AiMentorLessonFactory` to simplify and standardize test data creation for AI Mentor Lessons.
- Refactored and improved the **design of AI Mentor Lesson** for better structure and maintainability.
- fixed `updateSummary` in `ai.repository.ts`
> chore(SCS-573): Added tests for AI Repository.

- apps/web/app/modules/Admin/Groups/components/CreateGroupCard.tsx
- apps/web/app/modules/Admin/Users/Users.page.tsx
- apps/web/app/modules/Admin/Users/components/UserInfo.tsx
- apps/web/e2e/tests/admin/groups.spec.ts
- apps/web/e2e/tests/admin/language.spec.ts
[SCS-557](https://github.com/Selleo/mentingo/issues/557)
- Implemented E2E Playwright tests for assigning groups to users, both in bulk and individually  
- Added tests for creating, editing, and deleting groups  
- Covered language switching functionality  
- Verified that sidebar links are correctly translated after language change
> chore(SCS-557): created e2e tests for language switching and group crud

- .github/workflows/e2e.yml
- apps/web/app/api/mutations/useUpsertUserDetails.ts
- apps/web/app/locales/en/translation.json
- apps/web/app/locales/pl/translation.json
- apps/web/app/modules/Courses/CourseView/CourseViewSidebar/CourseProgress.tsx
- apps/web/e2e/tests/admin/admin-navigation.spec.ts
- apps/web/e2e/tests/admin/create-course.spec.ts
- apps/web/e2e/tests/admin/profile.spec.ts
- apps/web/e2e/tests/admin/settings.spec.ts
- apps/web/e2e/tests/content-creator/content-creator-navigation.spec.ts
- apps/web/e2e/tests/content-creator/settings.spec.ts
- apps/web/e2e/tests/student/course-workflow.spec.ts
- apps/web/e2e/tests/student/profile.spec.ts
- apps/web/e2e/tests/student/student-navigation.spec.ts
- apps/web/playwright.config.ts
[SCS-584](https://github.com/Selleo/mentingo/issues/584)
Fixed all existing E2E tests that were failing. Added LocalStack implementation for local S3 bucket on CI, so the image uploads can be tested.
> fix(SCS-584): failing e2e tests

- .github/workflows/deploy-webapp-staging.yml
Configured staging deployment to read SSO environment variables from GitHub Secrets
> chore(SCS): update staging workflow to use github secrets for SSO

- apps/api/src/seed/seed-prod.ts
- apps/api/src/seed/seed.ts
Fixed the production seeding script to ensure it works correctly on new instances by properly initializing settings for users and global configurations.
> fix(SCS): seed-prod script so everything works on new instances

- apps/web/app/locales/en/translation.json
- apps/web/app/locales/pl/translation.json
- apps/web/app/modules/Admin/Courses/Courses.page.tsx
[SCS-593](https://github.com/Selleo/mentingo/issues/593)
Improved error message for deletion of course when it's active. Now instead of a generic error message it will specify that the course needs to be drafted first.
Changed polish translations of dashboard to `Panel główny`
> chore(SCS-593): improved error message for course deletion of published course

- apps/web/app/modules/Courses/Lesson/Question/FillInTheBlanks/FillInTheBlanks.tsx
Fixed translations in fill in the blanks question
> fix: translations in fill in the blanks

- .github/workflows/deploy-learn-production.yml
- .github/workflows/deploy-webapp-production.yml
- .github/workflows/deploy-webapp-staging.yml
Fixed build to include tags, so the version can be set correctly
> fix: add fetching tags on deploy to save version in file

- apps/api/src/swagger/api-schema.json
- apps/api/src/user/schemas/updateUser.schema.ts
- apps/api/src/user/schemas/userQuery.ts
- apps/api/src/user/user.controller.ts
- apps/api/src/user/user.service.ts
- apps/web/app/api/generated-api.ts
- apps/web/app/modules/Admin/Users/CreateNewUser.page.tsx
- apps/web/app/modules/Admin/Users/Users.page.tsx
- apps/web/app/modules/Admin/Users/components/UserInfo.tsx
[627](https://github.com/Selleo/mentingo/issues/627)
- Fixed validation error while archiving user
- Changed default filter on `admin/users` page to be see only archived users
- Made labels stick to left in `CreateNewUser` page
> fix: archiving user and change default filter to archived user

- Makefile
Adjusted `Makefile` release script to only update changelog when tag starts with v
> chore: adjust makefile release for tag releases

- apps/api/src/courses/course.service.ts
- apps/api/src/stripe/stripeWebhook.handler.ts
[651](https://github.com/Selleo/mentingo/issues/651)
Fixed not enrolling user after successful payment.
https://github.com/user-attachments/assets/3b3c0da5-b187-418c-926f-b35008a53dd0
The tests bypass for Stripe payment was removed after conversation with @maciejhubert and @typeWolffo
> fix: enrolling to course on successful payment

- apps/web/app/modules/Admin/EditCourse/CourseLessons/components/ChaptersList.tsx
- apps/web/app/modules/Admin/EditCourse/CourseLessons/components/LessonCardList.tsx
[600](https://github.com/Selleo/mentingo/issues/600)
Fixed dnd item moving back when changing display order.
https://github.com/user-attachments/assets/b5d93c0f-71be-48c8-b488-b6922f950f4e
> fix: dnd item moving back when refetching current display order

- apps/web/app/modules/Auth/MFA.page.tsx
[695](https://github.com/Selleo/mentingo/issues/695)
Added check for current user on `MFA` page, so users don't get the infinite `Loader`
> fix: logout with mfa enabled triggering infinite loader

- apps/api/src/certificates/certificates.service.ts
- apps/api/src/settings/settings.service.ts
- apps/web/app/modules/Profile/Certificates/CertificatePreview.tsx
- apps/web/app/modules/Profile/Certificates/Certificates.tsx
[668](https://github.com/Selleo/mentingo/issues/668)
- Correct platform logo selection for certificates (API + Web)
- Unified background image rendering for certificates
https://github.com/user-attachments/assets/3638a632-afc2-42c7-b099-ef647bcd90a0
> fix(668): fixed platform logo and unified background image rendering for certificates

- apps/web/app/components/RichText/components/InsertLinkDialog.tsx
- apps/web/app/components/RichText/toolbar/EditorToolbar.tsx
- apps/web/app/locales/en/translation.json
- apps/web/app/locales/pl/translation.json
[679](https://github.com/Selleo/mentingo/issues/679)
Improved link inserting in `RichText` editor.
https://github.com/user-attachments/assets/45df5004-1b27-4aa9-88c7-3f9ab8617e5d
> feat: improve inserting links in rich text editor

- apps/web/app/modules/Auth/components/SocialLogin.tsx
Changed base redirect url of provider login to reflect current url instead of env variable
> fix: sso redirect on login to use current url

- apps/web/app/components/RichText/Editor.tsx
Fix for: https://github.com/Selleo/mentingo/issues/700
> fix: editor initial height

- apps/api/.eslintrc.js
- apps/api/src/utils/__tests__/isQuizAccessAllowed.spec.ts
[#715](https://github.com/orgs/Selleo/projects/31/views/1?pane=issue&itemId=131813514&issue=Selleo%7Cmentingo%7C715)
- Added unit tests for `isQuizAccessAllowed` function
> test: verify quiz access rules for attempts and cooldown

- apps/api/src/utils/__tests__/configValidator.spec.ts
[#719](https://github.com/orgs/Selleo/projects/31/views/1?pane=issue&itemId=131941312&issue=Selleo%7Cmentingo%7C719)
- Added unit tests for `configValidator` function
> test: add config validator unit tests

- apps/web/app/locales/en/translation.json
- apps/web/app/locales/pl/translation.json
Fixed day streak translations:
> refactor: day streak translations

- .github/workflows/deploy-learn-production.yml
[735](https://github.com/Selleo/mentingo/issues/735)
> fix: learn deploy workflow missing env
