Selleo/mentingo

apps/api/package.json
apps/api/src/app.module.ts
apps/api/src/auth/api/auth.controller.ts
apps/api/src/auth/auth.service.ts
apps/api/src/common/guards/refresh-token.guard.ts
apps/api/src/common/types.ts
apps/api/src/events/course/course-activity.event.ts
apps/api/src/events/events.module.ts
apps/api/src/events/index.ts
apps/api/src/events/lesson/lesson-completed.event.ts
apps/api/src/events/quiz/quiz-completed.event.ts
apps/api/src/events/user/user-activity.event.ts
apps/api/src/lessons/lessons.service.ts
apps/api/src/statistics/api/statistics.controller.ts
apps/api/src/statistics/handlers/statistics.handler.ts
apps/api/src/statistics/repositories/statistics.repository.ts
apps/api/src/statistics/schemas/userStats.schema.ts
apps/api/src/statistics/statistics.module.ts
apps/api/src/statistics/statistics.service.ts
apps/api/src/storage/migrations/0009_create_statistics.sql
apps/api/src/storage/migrations/meta/0009_snapshot.json
apps/api/src/storage/migrations/meta/_journal.json
apps/api/src/storage/schema/index.ts
apps/api/src/swagger/api-schema.json
apps/web/app/api/generated-api.ts
pnpm-lock.yaml

https://selleolabs.atlassian.net/browse/LC-371
https://selleolabs.atlassian.net/browse/LC-375
https://selleolabs.atlassian.net/browse/LC-376
https://selleolabs.atlassian.net/browse/LC-377
https://selleolabs.atlassian.net/browse/LC-378

feat: LC-368 stats backend

---

apps/web/app/modules/Courses/Lesson/LessonItems/File/Video.tsx

https://selleolabs.atlassian.net/browse/LC-382
https://github.com/cookpete/react-player#usage
> If your build system supports import() statements, use react-player/lazy to lazy load the appropriate player for the url you pass in. This adds several reactPlayer chunks to your output, but reduces your main bundle size.
https://github.com/user-attachments/assets/81421560-c078-48dc-a1a1-892673f6573e

feat: optimize video player import to use lazy loading in Video component

---

apps/api/src/statistics/repositories/statistics.repository.ts
apps/api/src/statistics/schemas/userStats.schema.ts
apps/api/src/statistics/statistics.service.ts
apps/api/src/swagger/api-schema.json
apps/web/app/api/generated-api.ts

[417](https://selleolabs.atlassian.net/jira/software/projects/LC/boards/3?selectedIssue=LC-417)
This PR adds courses completion to teacher statistics endpoint.

feat: courses completion for teacher statistics

---

apps/api/src/seed.ts
apps/api/src/statistics/repositories/statistics.repository.ts
apps/api/src/storage/migrations/0015_drop_course_id_constraint_on_course_students_stats.sql
apps/api/src/storage/migrations/meta/0015_snapshot.json
apps/api/src/storage/migrations/meta/_journal.json
apps/api/src/storage/schema/index.ts
apps/web/app/api/generated-api.ts

This PR adds teacher stats to seed.

feat: add teacher stats to seed

---

apps/api/src/chapter/chapter.controller.ts
apps/api/src/chapter/chapter.service.ts
apps/api/src/chapter/repositories/adminChapter.repository.ts
apps/api/src/chapter/repositories/chapter.repository.ts
apps/api/src/courses/course.controller.ts
apps/api/src/courses/course.service.ts
apps/api/src/courses/schemas/course.schema.ts
apps/api/src/swagger/api-schema.json
apps/web/app/api/generated-api.ts
apps/web/app/modules/Admin/Categories/Categories.page.tsx
apps/web/app/modules/Admin/EditCourse/CourseStatus/CourseStatus.tsx
apps/web/app/modules/Admin/EditCourse/CourseStatus/hooks/useCourseStatusForm.ts
apps/web/app/modules/Admin/EditCourse/CourseStatus/validators/courseStatusFormSchema.ts
apps/web/app/modules/Admin/EditCourse/EditCourse.tsx
apps/web/app/modules/Courses/CourseView/CourseView.page.tsx
apps/web/app/modules/Courses/CourseView/CourseViewMainCard.tsx
apps/web/app/modules/Courses/CourseView/LessonsList.tsx
apps/web/app/modules/Statistics/Admin/AdminStatistics.tsx
apps/web/app/modules/Statistics/Admin/components/EnrollmentChart.tsx

refactor: Resolve bugs related to teacher page

---

apps/api/src/chapter/repositories/adminChapter.repository.ts

https://selleolabs.atlassian.net/browse/LC-488
Fix problem with options array

fix: problem with options array

---

README.md
apps/api/src/scorm/schemas/scorm.schema.ts
apps/api/src/scorm/scorm.controller.ts
apps/api/src/seed/nice-data-seeds.ts
apps/api/src/swagger/api-schema.json
apps/reverse-proxy/Caddyfile
apps/web/app/api/api-client.ts
apps/web/app/api/generated-api.ts
apps/web/app/api/queries/admin/useScormMetaData.ts
apps/web/app/modules/Courses/CourseView/CourseView.page.tsx
apps/web/vite.config.ts

https://selleolabs.atlassian.net/browse/LC-481
- fixed scorm course view
- the `CourseView.page.tsx` will change as soon as the scorm will generate proper chapters for each resource
> [!WARNING]
> - changed Caddy reverse proxy to match our non-local reverse proxy (we need that to allow scorm api to connect with with `window` through iframe which requires the same origin)
>    - `https://app.lms.localhost` -> frontend
>    - `https://app.lms.localhost/api` -> backend
>
> You will need to update your Postman/Insomnia etc base url

refactor: update SCORM schemas and improve metadata handling in API responses

---

apps/api/src/scorm/scorm.module.ts
apps/api/src/scorm/services/scorm.service.ts
apps/web/app/modules/Courses/CourseView/CourseView.page.tsx

[LC-489](https://selleolabs.atlassian.net/browse/LC-489)
- now, during scorm processing the chapters are generated as in every other course
[LC-489]: https://selleolabs.atlassian.net/browse/LC-489?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: integrate Chapter and Lesson modules into SCORM processing

---

apps/api/src/courses/course.service.ts
apps/api/src/courses/schemas/showCourseCommon.schema.ts
apps/api/src/seed/seed-helpers.ts
apps/api/src/swagger/api-schema.json
apps/web/app/api/generated-api.ts
apps/web/app/modules/Admin/EditCourse/CourseSettings/CourseSettings.tsx
apps/web/app/modules/Admin/EditCourse/CourseSettings/hooks/useCourseSettingsForm.tsx
apps/web/app/modules/Admin/EditCourse/CourseSettings/validators/courseSettingsFormSchema.ts
apps/web/app/modules/Admin/EditCourse/EditCourse.tsx

https://selleolabs.atlassian.net/browse/LC-514)
Fix problem with display thumbnail in course settings

fix: thumbnail display

---

apps/web/app/modules/Courses/Lesson/Lesson.page.tsx
apps/web/app/modules/Courses/Lesson/LessonContent.tsx

[LC-523](https://selleolabs.atlassian.net/browse/LC-523)
- previous and next button are rendered conditionally based on lesson position in course
- in next pr the next button in last lesson probably will work differently to mark lesson as complete
[LC-523]: https://selleolabs.atlassian.net/browse/LC-523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: update lesson navigation to handle first and last lesson states in Course

---

apps/web/app/modules/Courses/Lesson/LessonSidebar.tsx

[LC-525](https://selleolabs.atlassian.net/browse/LC-525)
- now in chapters summary user can navigate only to the completed lessons
[LC-525]: https://selleolabs.atlassian.net/browse/LC-525?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: update lesson sidebar links to handle completed and not started statuses

---

apps/api/src/chapter/repositories/adminChapter.repository.ts
apps/api/src/courses/course.service.ts
apps/api/src/lesson/lesson.schema.ts
apps/api/src/lesson/services/lesson.service.ts
apps/api/src/storage/migrations/0010_add_isExternal_lesson_field.sql
apps/api/src/storage/migrations/meta/0010_snapshot.json
apps/api/src/storage/migrations/meta/_journal.json
apps/api/src/storage/schema/index.ts
apps/api/src/swagger/api-schema.json
apps/web/app/api/generated-api.ts
apps/web/app/components/VideoPlayer/Video.tsx
apps/web/app/components/VideoPlayer/VideoPlayer.tsx
apps/web/app/components/VideoPlayer/VideoPlayer.types.ts
apps/web/app/modules/Admin/EditCourse/CourseLessons/CourseLessons.tsx
apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/FileLessonForm/FileLessonForm.tsx
apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/FileLessonForm/hooks/useFileLessonForm.ts
apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/FileLessonForm/validators/fileLessonFormSchema.ts
apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/components/Breadcrumb.tsx
apps/web/app/modules/Admin/EditCourse/CourseLessons/components/ChaptersList.tsx
apps/web/app/modules/Admin/EditCourse/CourseLessons/components/LessonCard.tsx
apps/web/app/modules/Admin/EditCourse/EditCourse.types.ts
apps/web/app/modules/Courses/Lesson/LessonContent.tsx

[LC-531](https://selleolabs.atlassian.net/browse/LC-531)
- added external url handling in "file" lessons
[LC-531]: https://selleolabs.atlassian.net/browse/LC-531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: lc-531 external video

---

apps/api/src/courses/course.service.ts
apps/web/app/modules/Admin/AddCourse/AddCourse.tsx
apps/web/app/modules/Admin/AddCourse/hooks/useAddCourseForm.tsx
apps/web/app/modules/Admin/AddCourse/validators/addCourseFormSchema.ts

[LC-546](https://selleolabs.atlassian.net/browse/LC-546)
- fixed a bug that resulted in course thumbnails being sent to the course form with the wrong key
- fixed a bug that resulted in an image signed with a url being saved instead of the s3 key
[LC-546]: https://selleolabs.atlassian.net/browse/LC-546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: update AddCourse form to use fileUrl and thumbnailS3Key instead of imageUrl

---

apps/web/app/locales/en/translation.json
apps/web/app/locales/pl/translation.json
apps/web/app/modules/Admin/Courses/Courses.page.tsx

- turned off the 'upload scorm' button

chroe: add tooltip for disabled scorm upload button

---

apps/web/app/components/PriceInput/PriceInput.test.tsx
apps/web/app/components/PriceInput/PriceInput.tsx
apps/web/app/lib/formatters/priceFormatter.ts
apps/web/app/locales/en/translation.json
apps/web/app/locales/pl/translation.json
apps/web/app/modules/Admin/EditCourse/CoursePricing/CoursePricing.tsx
apps/web/app/modules/Admin/EditCourse/CoursePricing/hooks/useCoursePricingForm.ts
apps/web/app/modules/Admin/EditCourse/CoursePricing/validators/coursePricingFormSchema.ts

[LC-566](https://selleolabs.atlassian.net/browse/LC-582)
- fixed an issue when course price (in dollars) in input was not converted into cents
- created separated price input component with normalization (usage of `,` and `. `) and support for locale
- added test for price input component
[LC-566]: https://selleolabs.atlassian.net/browse/LC-566?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: lc-566 paid course price input

---

apps/web/app/locales/en/translation.json
apps/web/app/locales/pl/translation.json
apps/web/app/modules/Courses/CourseView/CourseViewSidebar/CourseProgress.tsx

[LC-581](https://selleolabs.atlassian.net/browse/LC-581)
[figma](https://www.figma.com/design/Hdnr93xRJ94FYgLr8jDICM/LMS?node-id=3020-26320&t=CWQsMbwrWEFRtcxi-1)
- adjusted the course details sidebar according to the figma design (removed student only buttons)
[LC-581]: https://selleolabs.atlassian.net/browse/LC-581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: adjust CourseProgress for admin roles in sidebar

---

apps/web/app/components/FileUploadInput/EmptyStateUpload.tsx
apps/web/app/components/FileUploadInput/FileUploadInput.tsx
apps/web/app/components/FileUploadInput/ImageUploadInput.tsx

[LC-585](https://selleolabs.atlassian.net/browse/LC-585)
- removed false info about supported file formats from file inputs
[LC-585]: https://selleolabs.atlassian.net/browse/LC-585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: simplify file formats in upload components for consistency and clarity

---

apps/api/src/courses/course.controller.ts
apps/api/src/courses/course.service.ts
apps/api/src/file/file.service.ts
apps/api/src/swagger/api-schema.json
apps/api/src/user/user.controller.ts
apps/api/src/user/user.service.ts
apps/web/app/api/generated-api.ts
apps/web/app/api/queries/useAvailableCourses.ts
apps/web/app/api/queries/useStudentCourses.ts
apps/web/app/api/queries/useUsers.ts
apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/QuizLessonForm.tsx
apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/components/AnswerSelectQuestion.tsx
apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/components/ScaleQuestion.tsx
apps/web/app/modules/Admin/Users/Users.page.tsx
apps/web/app/modules/Courses/Courses.page.tsx
apps/web/app/modules/Courses/Lesson/Lesson.page.tsx
apps/web/app/modules/Courses/Lesson/LessonSidebar.tsx
apps/web/app/modules/Courses/components/CourseList.tsx
apps/web/app/modules/Courses/components/CoursesCarousel.tsx
apps/web/app/modules/Dashboard/Courses/CourseList.tsx
apps/web/app/modules/Dashboard/Courses/CoursesCarousel.tsx

[LC-586](https://selleolabs.atlassian.net/jira/software/projects/LC/boards/3?selectedIssue=LC-586)
This PR adds missing thumbnail handler, user details and refactors courses response type.
[LC-586]: https://selleolabs.atlassian.net/browse/LC-586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add missing thumbnail and user details

---

apps/web/app/locales/en/translation.json
apps/web/app/locales/pl/translation.json
apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/TextLessonForm/TextLessonForm.tsx
apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/TextLessonForm/validators/useTextLessonFormSchema.ts

- added validation for lesson content to match with DB limits
[Sentry](https://selleolabs.sentry.io/issues/32061468/?project=4508880341106768)

fix: add max length validation for description field with user feedback in NewLesson form

---

apps/api/src/file/file.constants.ts

Increasing the limit of uploaded videos, as in real case videos will usually have more than 20MB

chore: increase file size upload limit

---

apps/web/app/locales/pl/translation.json

After encountering the confirmation modal for the first time I had no idea what any of those buttons do :)

fix: improve confusing translation in confirmation modal

---

apps/web/app/locales/en/translation.json
apps/web/app/locales/pl/translation.json
apps/web/app/modules/Profile/Profile.page.tsx
apps/web/app/modules/Profile/components/ProfileCard.tsx
apps/web/app/modules/Profile/components/index.ts

[SCS-486](https://github.com/Selleo/mentingo/issues/486)
Cleaned up profiles for admin, content creator and students to match the Figma design. The profiles work fully responsive.

refactor(SCS-486): clean up student and content creator profile according to design

---

.prettierrc.js
apps/api/src/courses/course.controller.ts
apps/api/src/courses/course.service.ts
apps/web/app/modules/Admin/EditCourse/EditCourse.tsx

[LC-500](https://github.com/Selleo/mentingo/issues/500)
Admin now can edit all courses. Content_creator cannot open edit mode and edit courses of others. Changed "ls" to "auto" in prettier
[LC-500]: https://selleolabs.atlassian.net/browse/LC-500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(SCS-500): Add roles and verifications to course editing

---

apps/api/src/s3/s3.service.ts

[SCS-552](https://github.com/Selleo/mentingo/issues/552)
Added forcePathStyle: true check to allow S3 to work on different hosting providers. Everything seems to be working now, didn't notice any bugs.

chore(SCS-552): added forcePathStyle true to S3Service

---

apps/api/src/auth/token.service.ts

[683](https://github.com/Selleo/mentingo/issues/683)
- Added path to cookie deletion for refresh token, as it was incorrectly deleted previously.
https://github.com/user-attachments/assets/9d7ce5f2-491c-4a3d-a0a2-0d169f663640

fix(683): Made logout not regenerate tokens

---

apps/api/src/auth/token.service.ts
apps/web/app/modules/Admin/EditCourse/EditCourse.tsx

[678](https://github.com/Selleo/mentingo/issues/678)
- Removed redirect on error in EditCourse, because randomly the first request for course returned 401, and then normally 200. 
- The video shows the cause of logout on tokens and how the error looks like after logout. And then I compared how it works when there is a redirect on error, and when it's removed
https://github.com/user-attachments/assets/6de81f08-1e4a-4417-af83-b716b067e084
The root issue is most likely located in token handling and logout. It seems that after logout, refresh token regenerates an access token, so you don't always get logged out correctly. And the tokens get glitched. Will be solved in another issue.

fix(678): Fixed redirect on course edit mode

---

apps/api/src/category/category.service.ts

[#728](https://github.com/orgs/Selleo/projects/31/views/1?pane=issue&itemId=131999559&issue=Selleo%7Cmentingo%7C728)
- Add checks if category already exists and return a meaningful error in `POST /api/category` entrypoint

fix: add checks if category already exists and return a meaningful error
